-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Dec 31, 2025 at 10:03 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `springboot_itineraryledger_kabengosafaris`
--

-- --------------------------------------------------------

--
-- Table structure for table `activities`
--

CREATE TABLE `activities` (
  `id` bigint(20) NOT NULL,
  `charging_basis` enum('FLAT_RATE','PER_DAY','PER_GROUP','PER_HOUR','PER_PERSON','PER_SESSION','PER_VEHICLE') DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `description` text DEFAULT NULL,
  `detailed_description` longtext DEFAULT NULL,
  `equipment_required` text DEFAULT NULL,
  `has_tariff` bit(1) NOT NULL,
  `is_active` bit(1) NOT NULL,
  `is_web_active` bit(1) NOT NULL,
  `maximum_participants` int(11) DEFAULT NULL,
  `minimum_age` int(11) DEFAULT NULL,
  `name` varchar(150) NOT NULL,
  `primary_image` varchar(500) DEFAULT NULL,
  `safety_information` text DEFAULT NULL,
  `season_availability` varchar(200) DEFAULT NULL,
  `slug` varchar(200) DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `activities`
--

INSERT INTO `activities` (`id`, `charging_basis`, `created_at`, `description`, `detailed_description`, `equipment_required`, `has_tariff`, `is_active`, `is_web_active`, `maximum_participants`, `minimum_age`, `name`, `primary_image`, `safety_information`, `season_availability`, `slug`, `tags`, `updated_at`) VALUES
(1, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Experience the thrill of spotting wildlife in their natural habitat during guided game drives through Tanzania\'s renowned national parks.', 'A game drive safari is the quintessential African safari experience. Conducted in specially designed 4x4 safari vehicles with pop-up roofs, these excursions take you through the vast savannas and diverse ecosystems of Tanzania\'s parks. Expert guides help you spot and identify the Big Five (lion, leopard, elephant, buffalo, and rhino) along with hundreds of other species including cheetahs, giraffes, zebras, and wildebeest. Game drives typically last 3-4 hours and are conducted during early morning (6:00-10:00 AM) or late afternoon (3:30-6:30 PM) when animals are most active. Full-day drives with packed lunches are also available. Your guide will share insights about animal behavior, ecology, and conservation efforts while ensuring you get the best photographic opportunities.', 'Binoculars, camera with telephoto lens, sunscreen, wide-brimmed hat, sunglasses, water bottle, light jacket for early morning', b'1', b'1', b'1', 6, 5, 'Game Drive Safari', NULL, 'Remain seated and quiet inside the vehicle at all times unless instructed otherwise by your guide. Do not stand up or lean out when near animals. Follow all instructions from your guide regarding safe distances. Never feed wildlife or attempt to touch animals.', 'Year-round; Best: June-October (dry season), December-March (calving season)', 'game-drive-safari', 'Safari, Wildlife, Big Five, Photography, Nature, Conservation, Serengeti, Ngorongoro', '2025-12-31 23:59:37.000000'),
(2, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Explore the wilderness on foot with armed guides, experiencing nature at ground level and tracking animals through the bush.', 'Walking safaris offer an intimate and thrilling way to experience Tanzania\'s wilderness. Led by armed park rangers and professional guides, you\'ll explore the bush on foot, learning to track animals, identify plants, read spoor (animal tracks), and understand the intricate relationships within the ecosystem. This activity engages all your senses - the smell of wild sage, the sound of birds, the texture of tree bark, and the excitement of encountering wildlife at their level. Walking safaris typically last 2-4 hours and cover 5-8 kilometers at a gentle pace with frequent stops for observations and explanations. You\'ll learn survival skills, understand animal behavior, and appreciate smaller details often missed from a vehicle - insects, plants, tracks, and signs of animal activity. The experience provides a deeper connection to nature and a sense of adventure that vehicle-based safaris cannot match.', 'Sturdy walking boots, long trousers, long-sleeved shirt (neutral colors), wide-brimmed hat, sunscreen, insect repellent, water bottle, small backpack, binoculars', b'1', b'1', b'1', 8, 12, 'Walking Safari', NULL, 'Always follow guide instructions. Stay together as a group. Walk in single file when instructed. Remain quiet and avoid sudden movements. Do not run if you encounter animals. The armed ranger is for your protection - follow their commands immediately.', 'Year-round; Best: June-October (dry season, easier walking)', 'walking-safari', 'Walking, Nature, Adventure, Tracking, Education, Bush Skills, Conservation', '2025-12-31 23:59:37.000000'),
(3, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Discover the nocturnal world of African wildlife on specially equipped night drives with spotlights.', 'Night game drives reveal a completely different side of the African wilderness. As darkness falls, nocturnal predators and prey emerge, creating thrilling opportunities to observe behaviors rarely seen during daylight hours. Equipped with powerful spotlights and red filters (which don\'t disturb animals), you\'ll search for leopards hunting, lions on the prowl, hyenas scavenging, genets, civets, bush babies, and nightjars. Your guide\'s spotlight will illuminate eyes reflecting in the darkness - each color indicating different species. Night drives typically run from 6:30 PM to 9:30 PM and offer cooler temperatures and dramatic encounters. You might witness a predator making a kill, hear the spine-chilling calls of hyenas, or see porcupines, aardvarks, and other rarely-seen nocturnal creatures. The experience includes stargazing opportunities in areas with minimal light pollution.', 'Warm jacket or fleece, long trousers, closed shoes, flashlight/headlamp, camera with good low-light capability, binoculars', b'1', b'1', b'1', 6, 8, 'Night Game Drive', NULL, 'Remain seated in the vehicle at all times. Do not shine personal lights at animals. Keep noise to a minimum. Follow guide instructions regarding when to use camera flash. Be aware that nocturnal predators are active.', 'Year-round; Best: June-October (dry season, better visibility)', 'night-game-drive', 'Night Safari, Nocturnal Wildlife, Predators, Adventure, Leopard, Photography', '2025-12-31 23:59:37.000000'),
(4, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Float silently over the Serengeti plains at sunrise, enjoying breathtaking aerial views of wildlife and landscapes.', 'A hot air balloon safari is an unforgettable bucket-list experience. Beginning before dawn, you\'ll watch the balloon inflation before climbing into the basket for a magical hour-long flight over the Serengeti or Tarangire. As the sun rises, casting golden light across the plains, you\'ll drift silently at treetop level, witnessing wildlife from a unique perspective - herds of elephants, grazing wildebeest, giraffes running beneath you, and predators on the hunt. The pilot can adjust altitude from just above the ground to several hundred feet, providing varied perspectives. The flight covers 10-20 kilometers depending on wind conditions. After landing, celebrate with a champagne breakfast in the bush, a tradition dating back to the first balloon flights. Professional photographers capture your experience, and you\'ll receive a flight certificate. This is one of the most spectacular and romantic ways to experience Tanzania\'s wilderness.', 'Warm layers (early morning can be cold), sturdy shoes, hat, sunglasses, camera, sunscreen', b'1', b'1', b'1', 16, 7, 'Hot Air Balloon Safari', NULL, 'Follow all pilot instructions. Remain standing during flight - no sitting allowed. Hold on during landing which can be bumpy. Pregnant women and people with serious back problems should not participate. Minimum height restrictions apply for children.', 'Year-round; Best: June-October, January-February (optimal weather and wildlife viewing)', 'hot-air-balloon-safari', 'Hot Air Balloon, Aerial Safari, Serengeti, Sunrise, Luxury, Romance, Photography, Champagne Breakfast', '2025-12-31 23:59:37.000000'),
(5, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Paddle peacefully through rivers and lakes, observing hippos, crocodiles, and abundant birdlife from the water.', 'Canoeing safaris offer a unique aquatic perspective on Tanzania\'s wildlife, particularly in areas like Arusha National Park\'s Momella Lakes or along the Rufiji River in Selous/Nyerere. Paddling in stable two-person canoes, you\'ll glide silently across calm waters, getting remarkably close to hippos (from a safe distance), observing crocodiles basking on riverbanks, and spotting diverse waterbirds including African fish eagles, kingfishers, herons, and storks. The experience typically lasts 2-3 hours and requires no previous canoeing experience - guides provide instruction and accompany you. You\'ll learn about aquatic ecosystems, see animals coming to drink, and enjoy the serenity of being on the water. This activity is excellent for photographers wanting different angles and for those seeking a peaceful, contemplative wildlife experience. Some locations offer sunset canoeing for spectacular lighting and increased wildlife activity.', 'Life jacket (provided), sun protection, quick-dry clothing, waterproof bag for camera/phone, water bottle, binoculars', b'1', b'1', b'1', 12, 10, 'Canoeing Safari', NULL, 'Always wear the provided life jacket. Follow guide instructions regarding distance from hippos and crocodiles. Stay together as a group. Do not stand up in the canoe. Avoid sudden movements or loud noises near hippos - they are territorial and dangerous.', 'Year-round; Best: June-October (lower water levels, wildlife concentrated)', 'canoeing-safari', 'Canoeing, Water Safari, Hippos, Birdwatching, Adventure, Peaceful, Photography', '2025-12-31 23:59:37.000000'),
(6, 'PER_GROUP', '2025-12-31 23:59:37.000000', 'Cruise along rivers and lakes in motorized boats, perfect for wildlife viewing and sunset experiences.', 'Boat safaris provide comfortable wildlife viewing from motorized vessels on Tanzania\'s rivers and lakes. Popular in Nyerere National Park (Selous), Lake Manyara, and along the Rufiji River, these cruises offer excellent opportunities to see hippos, crocodiles, elephants coming to drink, and an abundance of waterbirds. Boats accommodate 6-12 passengers and trips last 2-4 hours. Morning cruises focus on wildlife and bird activity, while sunset cruises offer spectacular photography opportunities with animals silhouetted against colorful skies. You\'ll see fish eagles diving for prey, monitor lizards on riverbanks, and pods of hippos wallowing in the water. Some boat safaris include fishing opportunities. The stable platform is excellent for photography, and the quiet electric motors allow close approaches to wildlife without disturbance. Refreshments are usually provided on longer cruises.', 'Sunscreen, hat, sunglasses, camera, binoculars, light jacket for wind, water bottle', b'1', b'1', b'1', 12, 5, 'Boat Safari', NULL, 'Remain seated while boat is moving. Keep hands inside the boat at all times. Do not lean over the sides. Follow guide instructions regarding safe distances from hippos. Lifejackets are available and should be worn by non-swimmers.', 'Year-round; Sunset cruises particularly stunning in dry season (June-October)', 'boat-safari', 'Boat Safari, River Cruise, Hippos, Crocodiles, Sunset, Birdwatching, Photography, Relaxing', '2025-12-31 23:59:37.000000'),
(7, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Enjoy catch-and-release fishing in designated park areas for tilapia, catfish, and other species.', 'Sport fishing in Tanzania\'s national parks and reserves is a regulated catch-and-release activity designed to provide recreational enjoyment while protecting fish populations. Available in select areas like Lake Manyara, Rubondo Island, and some Rufiji River sections, fishing trips last 3-4 hours and target species including tilapia, catfish (vundu), tiger fish, and others. Experienced guides provide equipment (rods, reels, bait) and instruction for beginners, while experienced anglers can bring their own gear. You\'ll learn about aquatic ecosystems, fish behavior, and conservation efforts while enjoying the peaceful experience of fishing in stunning natural settings. All catches must be released unharmed, and barbless hooks are required. The activity combines fishing with wildlife viewing as you\'ll see hippos, crocodiles, and birds while waiting for bites. Photography of catches before release is encouraged.', 'Hat, sunscreen, sunglasses, camera, water bottle, light snacks. Fishing equipment provided or bring your own.', b'1', b'1', b'1', 6, 12, 'Sport Fishing', NULL, 'Use only barbless hooks. Release all fish carefully and immediately. Do not fish near hippos or crocodiles. Follow guide instructions regarding safe fishing locations. Wear sunscreen and stay hydrated.', 'Year-round; Best: June-October (clearer water, fish more active)', 'sport-fishing', 'Fishing, Catch and Release, Conservation, Lake Manyara, Peaceful, Recreation', '2025-12-31 23:59:37.000000'),
(8, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Challenge yourself with guided treks through mountain forests and highlands, including routes on Kilimanjaro and surrounding peaks.', 'Mountain trekking in Tanzania ranges from day hikes to multi-day expeditions. While Kilimanjaro summit attempts require separate specialized permits, this activity covers trekking on Kilimanjaro\'s lower slopes, Mount Meru, the Usambara Mountains, and Udzungwa Mountains. Guided treks typically last 4-8 hours and take you through diverse ecosystems - montane forests with colobus monkeys, bamboo zones, heath, and moorland. You\'ll experience dramatic elevation changes, waterfalls, unique flora including giant lobelias, and stunning panoramic views. Trails vary in difficulty from moderate to challenging, with options for different fitness levels. Guides provide information about geology, plants, animals, and local culture. Some treks include visits to local communities. Porters can carry heavier gear, and camping options are available for multi-day treks. The cooler mountain climate provides relief from lowland heat.', 'Hiking boots with ankle support, layered clothing (temperature varies with altitude), rain jacket, walking poles, backpack, water bottle (2L), snacks, sunscreen, first aid kit', b'1', b'1', b'1', 10, 14, 'Mountain Trekking', NULL, 'Acclimatize properly to altitude. Stay hydrated. Inform guides of any health issues. Walk at a steady, sustainable pace. Use walking poles on steep sections. Be prepared for rapid weather changes. Stay on marked trails.', 'Year-round; Best: June-October, January-February (dry seasons, best visibility)', 'mountain-trekking', 'Trekking, Hiking, Mountains, Kilimanjaro, Mount Meru, Fitness, Adventure, Views', '2025-12-31 23:59:37.000000'),
(9, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Walk through the forest canopy on suspended bridges, experiencing the treetop ecosystem and stunning views.', 'Canopy walks provide a thrilling perspective on Tanzania\'s forests from elevated walkways 20-40 meters above the ground. Located in parks like Udzungwa Mountains, these suspended bridges and platforms allow you to walk through the treetops, experiencing the forest from the monkeys\' perspective. The walkway sways gently, adding to the excitement while remaining completely safe. From this vantage point, you\'ll observe different bird species, colobus monkeys, butterflies, and unique plants that thrive in the canopy layer. The experience lasts 1-2 hours and includes educational information about forest ecology, the importance of canopy layers, and conservation. Stunning views extend across the forest to distant mountains. The activity is suitable for most fitness levels, though those with severe fear of heights should consider carefully. Sunrise and sunset canopy walks offer special lighting and increased animal activity.', 'Comfortable walking shoes, light clothing, hat, sunscreen, camera, water bottle, binoculars', b'1', b'1', b'1', 15, 8, 'Canopy Walk', NULL, 'Follow guide instructions. Hold handrails at all times. Walk carefully on bridges. Do not jump or rock the walkway. Maximum weight limits apply. Not suitable for those with extreme fear of heights or serious balance issues.', 'Year-round; Best: June-October (clearer weather, better views)', 'canopy-walk', 'Canopy Walk, Forest, Heights, Adventure, Monkeys, Birdwatching, Udzungwa, Views', '2025-12-31 23:59:37.000000'),
(10, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Explore diverse ecosystems on guided nature hikes, from coastal forests to highland trails.', 'Nature hiking offers immersive experiences through Tanzania\'s varied ecosystems beyond game viewing. These guided walks, typically 2-4 hours, focus on understanding the intricate relationships between plants, animals, and environment. You\'ll visit waterfalls, crater lakes, hot springs, caves, and unique geological formations. Guides point out medicinal plants, edible fruits, animal tracks, and explain traditional uses of natural resources. Hikes might include visiting archaeological sites, rock paintings, or historical locations. The pace is leisurely with frequent stops for observations, photography, and explanations. Popular locations include Lake Manyara\'s escarpment trails, Arusha National Park\'s forest paths, and Mahale Mountains\' chimp trekking routes. You\'ll develop tracking skills, learn bird calls, and understand ecosystem dynamics. Some hikes offer cultural elements, visiting local communities or farms.', 'Comfortable hiking shoes, light breathable clothing, hat, sunscreen, insect repellent, camera, water bottle, small backpack', b'1', b'1', b'1', 12, 8, 'Nature Hiking', NULL, 'Stay with the group. Inform guide of any fitness limitations. Bring adequate water. Wear appropriate footwear to prevent slips. Be aware of insects and plants that may cause irritation. Follow safety briefings.', 'Year-round; Best: June-October (dry trails, pleasant weather)', 'nature-hiking', 'Hiking, Nature, Waterfalls, Ecosystem, Education, Photography, Forest, Culture', '2025-12-31 23:59:37.000000'),
(11, 'PER_GROUP', '2025-12-31 23:59:37.000000', 'Experience authentic Tanzanian culture through visits to Maasai, Hadzabe, Datoga, and other traditional communities.', 'Cultural village tours provide meaningful interactions with Tanzania\'s indigenous communities, offering insights into traditional lifestyles that have endured for centuries. Maasai village visits are most common, where you\'ll participate in traditional dances, learn about cattle herding, visit homes (bomas), observe traditional medicine practices, and purchase authentic crafts. Hadzabe visits with the last remaining hunter-gatherer tribe include demonstrations of bow-making, traditional hunting techniques, and gathering honey. Datoga communities showcase metalworking and jewelry-making. Tours last 2-3 hours and are conducted respectfully with community consent, ensuring tourism benefits local people directly. You\'ll learn about social structures, ceremonies, traditional clothing, food preparation, and challenges of maintaining culture in modern times. Photography is usually permitted, and guides facilitate communication. These experiences foster cultural understanding and support community development.', 'Respectful clothing (covering shoulders and knees), camera, cash for purchasing crafts, water bottle, hat', b'1', b'1', b'1', 15, 6, 'Cultural Village Tours', NULL, 'Dress respectfully. Ask permission before photographing people. Do not give children candy or money directly. Purchase crafts to support the community. Listen attentively and show respect for different customs. Follow guide instructions regarding appropriate behavior.', 'Year-round', 'cultural-village-tours', 'Culture, Maasai, Hadzabe, Datoga, Traditional, Community, Crafts, Dance, Education', '2025-12-31 23:59:37.000000'),
(12, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Explore the \"Cradle of Mankind\" where some of the earliest human ancestor fossils were discovered.', 'Olduvai Gorge, often called the \"Cradle of Mankind,\" is one of the world\'s most important paleoanthropological sites. Located in the Ngorongoro Conservation Area, this steep-sided ravine has yielded fossils and stone tools dating back 2 million years, providing crucial evidence of human evolution. Your visit includes the small museum displaying replica fossils, stone tools, and information about Louis and Mary Leakey\'s groundbreaking discoveries. Expert guides explain the significance of findings including Homo habilis, Australopithecus boisei, and various animal fossils. You\'ll walk along the gorge rim, viewing the different geological layers representing millions of years of history. The site offers spectacular views and fascinating insights into human origins. The visit typically lasts 1.5-2 hours and combines education with stunning landscapes. Ongoing excavations occasionally add new discoveries.', 'Comfortable walking shoes, hat, sunscreen, camera, water bottle, notebook for educational information', b'1', b'1', b'1', 30, 8, 'Olduvai Gorge Visit', NULL, 'Stay on designated paths. Do not remove any rocks or materials. Follow museum rules regarding photography. Bring sun protection as there is limited shade. Respect the archaeological significance of the site.', 'Year-round', 'olduvai-gorge-visit', 'Archaeology, Human Evolution, Olduvai, Leakey, History, Education, Science, Fossils', '2025-12-31 23:59:37.000000'),
(13, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Visit the site of 3.6 million-year-old hominid footprints preserved in volcanic ash.', 'The Laetoli footprints are among the most remarkable paleoanthropological discoveries ever made. Preserved in volcanic ash 3.6 million years ago, these footprints provide definitive evidence that early human ancestors walked upright. Located near Olduvai Gorge, visits to the actual footprint site require special arrangements and are limited to preserve the delicate fossil evidence. Most visitors view detailed replicas at the Olduvai Museum and learn about the discovery\'s significance through expert presentations. The footprints were made by three individuals - possibly a family group - walking across wet volcanic ash after an eruption. When the ash hardened, it preserved their footsteps for millions of years. The discovery revolutionized understanding of human evolution, proving bipedalism evolved earlier than previously thought. Guides explain the scientific methods used to date and interpret the footprints.', 'Comfortable walking shoes, hat, sunscreen, camera, water bottle, interest in human evolution', b'1', b'1', b'1', 20, 10, 'Laetoli Footprints Visit', NULL, 'Follow all conservation guidelines. Photography may be restricted at the actual site. Do not touch any fossil material. Respect the scientific importance of the location. Listen to educational briefings.', 'Year-round (museum); Special site visits by arrangement only', 'laetoli-footprints-visit', 'Archaeology, Human Evolution, Footprints, Science, Education, Fossils, History', '2025-12-31 23:59:37.000000'),
(14, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Track and observe wild chimpanzees in their natural rainforest habitat in Mahale Mountains or Gombe Stream.', NULL, 'Sturdy hiking boots, long trousers, long-sleeved shirt, rain jacket, gardening gloves, water bottle', b'1', b'1', b'1', 6, 15, 'Chimpanzee Trekking', NULL, NULL, 'Year-round; Best: May-October (drier, easier trekking)', 'chimpanzee-trekking', 'Chimpanzee, Primates, Mahale, Gombe, Jane Goodall, Rainforest, Wildlife, Tracking', '2025-12-31 23:59:37.000000'),
(15, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Participate in conservation efforts by tracking black rhinos on foot in protected sanctuaries.', NULL, 'Sturdy hiking boots, neutral-colored clothing, hat, sunscreen, binoculars, camera with telephoto lens', b'1', b'1', b'1', 6, 16, 'Rhino Tracking', NULL, NULL, 'Year-round; Success rate varies by season', 'rhino-tracking', 'Rhino, Conservation, Endangered Species, Tracking, Wildlife, Protection, Ngorongoro', '2025-12-31 23:59:37.000000'),
(16, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Discover Tanzania\'s incredible avian diversity with over 1,100 species including numerous endemic and migratory birds.', NULL, 'Binoculars (essential), bird field guide, camera with telephoto lens, notebook, hat, sunscreen', b'1', b'1', b'1', 8, 10, 'Bird Watching Safaris', NULL, NULL, 'Year-round; Palearctic migrants present November-April; Resident breeders best October-April', 'bird-watching-safaris', 'Birdwatching, Ornithology, Endemic Species, Flamingos, Nature, Photography, Conservation', '2025-12-31 23:59:37.000000'),
(17, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Explore parks and conservation areas by mountain bike, combining exercise with wildlife viewing.', NULL, 'Comfortable cycling clothes, closed sports shoes, helmet (provided), sunscreen, sunglasses, water bottle', b'1', b'1', b'1', 10, 14, 'Cycling Safaris', NULL, NULL, 'Year-round; Best: June-October (dry trails, cooler temperatures)', 'cycling-safaris', 'Cycling, Mountain Biking, Adventure, Fitness, Eco-Tourism, Active Safari', '2025-12-31 23:59:37.000000'),
(18, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Experience the African wilderness on horseback, getting close to wildlife in a unique and peaceful way.', NULL, 'Long trousers, boots with small heel or riding boots, hat with chin strap, sunscreen, camera', b'1', b'1', b'1', 8, 12, 'Horse Riding Safaris', NULL, NULL, 'Year-round; Best: June-October (optimal weather)', 'horse-riding-safaris', 'Horse Riding, Equestrian, Adventure, Wildlife, Unique Safari, Romance, Photography', '2025-12-31 23:59:37.000000'),
(19, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Improve your wildlife photography skills with professional guidance during dedicated photo safaris.', NULL, 'DSLR or mirrorless camera, telephoto lens (300mm+), wide-angle lens, extra batteries, memory cards, laptop', b'1', b'1', b'1', 6, 16, 'Photography Workshops', NULL, NULL, 'Year-round; Great Migration timing (July-October) offers spectacular opportunities', 'photography-workshops', 'Photography, Wildlife Photography, Workshop, Education, Professional, Great Migration', '2025-12-31 23:59:37.000000'),
(20, 'PER_VEHICLE', '2025-12-31 23:59:37.000000', 'Descend into the world\'s largest intact volcanic caldera for unparalleled wildlife viewing.', NULL, 'Warm layers, rain jacket, camera with good zoom, binoculars, picnic lunch, water, sunscreen', b'1', b'1', b'1', 6, 5, 'Ngorongoro Crater Descent', NULL, NULL, 'Year-round; Wildlife concentrated year-round due to enclosed ecosystem', 'ngorongoro-crater-descent', 'Ngorongoro, Crater, Big Five, Black Rhino, Caldera, World Heritage, Spectacular Views', '2025-12-31 23:59:37.000000'),
(21, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Witness the mysterious moving sand dunes that slowly travel across the Ngorongoro plains.', NULL, 'Comfortable walking shoes, hat, sunscreen, sunglasses, camera, water bottle, scarf', b'1', b'1', b'1', 25, 6, 'Shifting Sands Visit', NULL, NULL, 'Year-round', 'shifting-sands-visit', 'Geology, Shifting Sands, Ngorongoro, Maasai Culture, Unique Phenomenon, Photography', '2025-12-31 23:59:37.000000'),
(22, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Enjoy gourmet dining experiences in the wilderness, including bush breakfasts, picnic lunches, and candlelit dinners under African skies.', 'Bush meals transform dining into unforgettable safari experiences. Bush breakfasts after early morning balloon safaris or game drives feature freshly cooked meals under acacia trees with white-tablecloth service in the wilderness. Bush lunches during full-day safaris are enjoyed at scenic spots - beside rivers, under shade trees, overlooking valleys. Some lodges offer candlelit dinners under the stars, complete with traditional dancers, bonfire, and gourmet multi-course meals. These experiences combine exceptional food with spectacular settings and often include wildlife sightings - elephants approaching at dusk, nocturnal animals beginning their activities. Professional staff set up elegant dining areas in remote locations, creating magical moments that epitomize luxury safari experiences.', 'Light jacket for cooler weather, camera, appropriate dining attire (smart casual), binoculars', b'1', b'1', b'1', 20, 5, 'Bush Meals', NULL, 'Follow staff instructions regarding wildlife safety. Do not wander from dining areas. Keep food secured from wildlife. Stay within designated safe zones. Bring warm layers for evening meals.', 'Year-round; Dry season (June-October) most reliable for outdoor dining events', 'bush-meals', 'Bush Meals, Wilderness Dining, Luxury, Gourmet, Safari Experience, Romance, Photography', '2025-12-31 23:59:37.000000'),
(23, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Experience spectacular African sunsets with cocktails and snacks at scenic viewpoints, a cherished safari tradition.', 'Sundowners are a quintessential safari ritual where guests gather at scenic viewpoints as the sun sets, enjoying cocktails, soft drinks, and canapés while watching the golden hour transform the African landscape. Guides select perfect locations - atop hills with panoramic views, beside waterholes where animals gather, or on open plains with unobstructed horizons. As the sun descends, casting warm golden and orange hues across the savanna, you\'ll witness the magical transition from day to night. Wildlife becomes silhouetted against colorful skies, and nocturnal animals begin their activities. The experience typically lasts 45-60 minutes, providing exceptional photography opportunities during the golden hour. Stories are shared, the day\'s sightings discussed, and the beauty of Africa\'s wilderness celebrated. Some sundowners include traditional music or cultural performances. It\'s a peaceful, romantic way to end safari days.', 'Light jacket or wrap (temperatures drop after sunset), camera, sunglasses, binoculars', b'1', b'1', b'1', 15, 8, 'Sundowner', NULL, 'Stay within designated areas. Follow guide instructions. Do not wander off alone. Be aware of wildlife activity at dusk. Enjoy alcohol responsibly. Bring warm clothing as temperatures drop quickly after sunset.', 'Year-round; Most spectacular during dry season (June-October) with clearer skies', 'sundowner', 'Sundowner, Sunset, Cocktails, Safari Tradition, Photography, Romance, Golden Hour, Relaxation', '2025-12-31 23:59:37.000000'),
(24, 'PER_SESSION', '2025-12-31 23:59:37.000000', 'Attend educational presentations by expert naturalists covering ecology, conservation, and wildlife behavior.', NULL, 'Notebook, camera for presentation materials, curiosity and questions', b'1', b'1', b'1', 30, 8, 'Guided Nature Lectures', NULL, NULL, 'Year-round; Often scheduled in afternoon/evening', 'guided-nature-lectures', 'Education, Conservation, Ecology, Wildlife, Lectures, Learning, Nature, Science', '2025-12-31 23:59:37.000000'),
(25, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Educational programs designed specifically for children to learn about wildlife, conservation, and bush skills.', NULL, 'Comfortable outdoor clothing, closed shoes, hat, sunscreen, water bottle, notebook and pencils', b'1', b'1', b'1', 12, 6, 'Junior Ranger Programs', NULL, NULL, 'Year-round', 'junior-ranger-programs', 'Children, Education, Junior Rangers, Conservation, Family, Learning, Adventure, Fun', '2025-12-31 23:59:37.000000'),
(26, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Park entrance fee providing access to park amenities and the opportunity to experience game drives, walking safaris, and the natural scenery and wildlife.', 'The entrance fee is a mandatory charge for accessing Tanzania\'s national parks and conservation areas. This fee supports park management, conservation efforts, anti-poaching operations, infrastructure maintenance, and community development programs. Upon payment, visitors receive access to the park\'s full range of offerings including game drives, designated picnic areas, viewing points, and visitor centers. The fee varies by park and visitor category (international, resident, East African). Some parks offer multi-day passes at discounted rates. Revenue from entrance fees directly contributes to wildlife protection and habitat preservation. Park rangers at entrance gates provide maps, safety briefings, and current wildlife sighting information. The entrance process includes vehicle registration and visitor documentation for security and conservation monitoring purposes.', 'Valid identification, park permit or booking confirmation, payment method (cash USD or card where accepted)', b'1', b'1', b'0', 999, 0, 'Entrance', NULL, 'Keep your entrance receipt as it may be checked at various points within the park. Follow all park rules and regulations. Respect gate opening and closing times. Ensure your vehicle is registered if driving yourself.', 'Year-round; All parks require entrance fees regardless of season', 'entrance', 'Entrance Fee, Park Access, Conservation Fee, Mandatory, Park Services, Gate Fee', '2025-12-31 23:59:37.000000'),
(27, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Hire a professional park ranger or guide to accompany you during activities, providing safety, expert guidance, and in-depth knowledge about wildlife and conservation.', 'Park rangers are trained professionals who enhance safari experiences through their extensive knowledge of wildlife behavior, tracking skills, and understanding of park ecosystems. Hiring a ranger is mandatory for certain activities like walking safaris, hiking in restricted areas, and visiting specific conservation zones. Rangers ensure visitor safety, particularly in areas with dangerous wildlife, and are trained in first aid and emergency response. They provide expert interpretation of animal behavior, identify species, explain conservation challenges, and share insights about anti-poaching efforts. Rangers know the best locations for wildlife sightings based on recent activity and seasonal patterns. Many rangers have specialized knowledge in areas like ornithology, botany, or large mammal behavior. Their presence supports local communities as many rangers are recruited from nearby villages. Ranger fees contribute to their salaries and professional development, supporting conservation career pathways.', 'None required - ranger provides guidance and safety equipment as needed', b'1', b'1', b'0', 20, 0, 'Ranger', NULL, 'Always follow your ranger\'s instructions immediately. Rangers are trained in wildlife safety and emergency procedures. They carry communication equipment and first aid supplies. Do not separate from your ranger during guided activities.', 'Year-round; Essential service available daily during park operating hours', 'ranger', 'Ranger, Guide, Safety, Expert Knowledge, Conservation, Wildlife Tracking, Professional Guide', '2025-12-31 23:59:37.000000'),
(28, 'PER_DAY', '2025-12-31 23:59:37.000000', 'Professional or amateur filming permits for documentaries, commercial projects, or personal videos within park boundaries.', 'Filming in Tanzania\'s national parks requires special permits beyond standard entrance fees, with different categories for commercial productions, documentaries, student projects, and personal filming. Commercial filming (for broadcast, advertising, or sale) requires comprehensive permits obtained weeks in advance through Tanzania National Parks Authority (TANAPA) or relevant conservation authorities. Documentary filmmakers must submit detailed proposals including project scope, intended use, crew size, and equipment lists. Permits specify allowed filming locations, times, and any restrictions to protect wildlife and minimize disturbance. Professional productions may require ranger escorts and may be restricted during sensitive periods like calving seasons. Drone filming has strict regulations and is prohibited in many areas without special authorization. Amateur filming for personal use (wedding videos, travel vlogs) typically requires simpler permits with lower fees. All filming must adhere to ethical guidelines - no harassment of wildlife, no manipulation of animal behavior, and no filming of sensitive conservation operations. Revenue from filming permits supports conservation and can provide significant funding for park management.', 'Filming equipment, permit documentation, letter of intent (for commercial), insurance documentation, equipment list', b'1', b'1', b'1', 30, 18, 'Filming', NULL, 'Maintain safe distances from wildlife while filming. Do not use artificial lights that disturb animals. Follow all park regulations. Secure equipment during transport. Have insurance coverage for crew and equipment. Respect wildlife and environmental protocols.', 'Year-round; Advance booking required for commercial projects (4-8 weeks); Some restrictions during sensitive wildlife periods', 'filming', 'Filming, Photography, Documentary, Commercial Production, Permits, Media, Conservation', '2025-12-31 23:59:37.000000'),
(29, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Challenge yourself with rock climbing in parks featuring rugged landscapes and dramatic cliff formations, particularly in Udzungwa Mountains National Park.', 'Rock climbing in Tanzania\'s national parks offers thrilling vertical adventures in stunning natural settings. Udzungwa Mountains National Park is the premier destination, featuring dramatic escarpments, rock faces, and boulder fields with routes ranging from beginner-friendly to expert-level technical climbs. The park\'s unique geology creates excellent climbing conditions with solid rock formations and varied route options. Climbs range from sport climbing on bolted routes to traditional climbing requiring full gear placement, and bouldering on massive granite blocks. Professional guides assess climber abilities and recommend appropriate routes. Climbs typically last 4-6 hours including instruction, safety briefings, and multiple ascent attempts. The experience combines physical challenge with spectacular views across the Eastern Arc Mountains and opportunities to see unique wildlife including endemic primates visible from cliff faces. Some routes pass through forest canopies offering unusual perspectives on the ecosystem. All climbing follows Leave No Trace principles to protect fragile cliff ecosystems. Guides provide all necessary technical equipment including ropes, harnesses, helmets, and climbing shoes.', 'Provided: helmet, harness, climbing shoes, ropes, carabiners, belay devices. Bring: athletic clothing, closed-toe shoes for approach hikes, water bottle, sunscreen, climbing gloves (optional)', b'1', b'1', b'1', 6, 12, 'Rock Climbing', NULL, 'Previous climbing experience recommended but not mandatory - beginners receive thorough instruction. Follow all safety protocols. Use all provided safety equipment correctly. Inform guides of any medical conditions. Stay hydrated. Check weather conditions - climbing cancelled in rain or high winds. Proper physical fitness required.', 'Year-round; Best: June-October and January-February (dry seasons, better rock conditions and grip)', 'rock-climbing', 'Rock Climbing, Adventure, Udzungwa Mountains, Mountaineering, Technical Climbing, Bouldering, Extreme Sports', '2025-12-31 23:59:37.000000'),
(30, 'PER_PERSON', '2025-12-31 23:59:37.000000', 'Learn the ancient art of tracking wildlife with expert guides, following specific animals like lions, elephants, or rhinos through their natural habitats.', 'Wildlife tracking is an immersive experience that teaches the traditional skills used by indigenous trackers and modern conservationists to locate and monitor animals. Led by expert trackers with years of field experience, you\'ll learn to read signs invisible to untrained eyes - fresh footprints in soft soil, bent grass indicating an animal\'s path, scratch marks on trees, dung composition and freshness, disturbed vegetation, and scent markers. Trackers teach you to estimate when an animal passed through an area, identify individual animals by unique spoor characteristics, and understand territorial behaviors. The experience typically focuses on tracking specific species - lion prides, elephant herds, black rhinos, or leopards - following their movements from dawn. You\'ll learn about animal behavior patterns, preferred habitats, feeding signs, and social structures. Tracking combines intellectual challenge with physical activity, requiring observation skills, logical deduction, and patience. Modern tracking incorporates technology like GPS collars and radio telemetry for conservation research, which you may observe. The activity provides deep insights into predator-prey dynamics and ecosystem health. Successful tracks that lead to sightings create profound satisfaction beyond typical game drives.', 'Comfortable walking boots, neutral-colored clothing (avoid bright colors), hat, sunscreen, binoculars, camera, water bottle, notebook for learning tracking signs', b'1', b'1', b'1', 6, 14, 'Wildlife Tracking', NULL, 'Always stay with your tracker. This activity involves close wildlife encounters - follow all instructions immediately. Maintain silence when tracking. Be prepared for long walks (5-10km) over varied terrain. Inform guides of fitness levels and any limitations. Wear sturdy footwear. Carry adequate water. Potentially dangerous wildlife may be encountered - tracker safety protocols are mandatory.', 'Year-round; Best: June-October (dry season - clearer tracks, concentrated wildlife); Early morning sessions most successful', 'wildlife-tracking', 'Wildlife Tracking, Conservation, Animal Behavior, Bushcraft, Expert Guides, Predators, Footprints, Field Skills', '2025-12-31 23:59:37.000000');

-- --------------------------------------------------------

--
-- Table structure for table `parks`
--

CREATE TABLE `parks` (
  `id` bigint(20) NOT NULL,
  `access_information` text DEFAULT NULL,
  `best_time_to_visit` varchar(100) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `district` varchar(100) DEFAULT NULL,
  `ecosystem` longtext DEFAULT NULL,
  `elevation` varchar(50) DEFAULT NULL,
  `full_description` longtext NOT NULL,
  `history` longtext DEFAULT NULL,
  `internal_notes` longtext DEFAULT NULL,
  `is_active` bit(1) NOT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `location` text DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `opening_hours` text DEFAULT NULL,
  `park_type` enum('CONSERVATION_AREA','FOREST_RESERVE','GAME_RESERVE','MARINE_PARK','NATIONAL_PARK','NATURE_RESERVE','WILDLIFE_RESERVE') NOT NULL,
  `primary_image` varchar(500) DEFAULT NULL,
  `region` varchar(100) DEFAULT NULL,
  `short_description` text NOT NULL,
  `size` varchar(50) DEFAULT NULL,
  `slug` varchar(150) DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `vegetation` longtext DEFAULT NULL,
  `wildlife` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `parks`
--

INSERT INTO `parks` (`id`, `access_information`, `best_time_to_visit`, `created_at`, `district`, `ecosystem`, `elevation`, `full_description`, `history`, `internal_notes`, `is_active`, `latitude`, `location`, `longitude`, `name`, `opening_hours`, `park_type`, `primary_image`, `region`, `short_description`, `size`, `slug`, `tags`, `updated_at`, `vegetation`, `wildlife`) VALUES
(1, 'Accessible by road from Arusha (8-9 hours) or by air to Seronera, Kogatende, or Lobo airstrips. Multiple entry gates including Naabi Hill, Ndabaka, and Ikoma.', 'June to October (dry season for wildlife viewing), January to February (calving season)', '2025-12-31 23:59:37.000000', 'Serengeti', 'Grassland savanna, acacia woodlands, riverine forests, and open plains. The ecosystem supports diverse habitats from short grass plains to kopjes (rocky outcrops).', '920-1,850 meters', 'Serengeti National Park is a vast ecosystem in north-central Tanzania. Established in 1951, it covers 14,763 square kilometers of grassland plains, savanna, riverine forest, and woodlands. The park is divided into three regions: Serengeti Plains, Western Corridor, and Northern Serengeti. It borders the Maasai Mara National Reserve in Kenya to the north. The park is home to the largest lion population in Africa and hosts the spectacular Great Migration, one of the most impressive natural events on Earth. The name \"Serengeti\" comes from the Maasai language and means \"endless plains\".', 'Established in 1951 and designated as a UNESCO World Heritage Site in 1981. The area was first protected as a game reserve in 1929 before being upgraded to national park status.', NULL, b'1', -2.3333000, 'Northern Tanzania, 335 km northwest of Arusha', 34.8333000, 'Serengeti National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Mara and Simiyu', 'One of the most famous wildlife sanctuaries in the world, known for the annual Great Migration of over 1.5 million wildebeest and 250,000 zebras.', '14,763 km²', 'serengeti-national-park', 'Big Five, Great Migration, Safari, Wildlife, UNESCO World Heritage, Lion, Wildebeest, Zebra, Kopjes, Savanna', '2025-12-31 23:59:37.000000', 'Grassland plains dominate with scattered acacia trees, particularly umbrella acacias. Western corridor features riverine forests along the Grumeti River. Kopjes support unique plant communities.', 'Home to the Big Five (lion, leopard, elephant, buffalo, rhinoceros) and hosts the Great Migration of over 2 million wildebeest, zebras, and gazelles. The park has Africa\'s largest lion population with over 3,000 lions. Other species include cheetahs, hyenas, giraffes, hippos, crocodiles, and over 500 bird species.'),
(2, 'Accessible by road from Arusha (3-4 hours). Main entrance at Lodoare Gate. Can be combined with Serengeti visits via Naabi Hill Gate.', 'June to October (dry season), December to March (green season)', '2025-12-31 23:59:37.000000', 'Ngorongoro', 'Highland plains, savanna, savanna woodlands, forests, and the volcanic crater ecosystem. Includes soda lakes, swamps, and montane forests on crater rims.', '1,030-3,648 meters (Loolmalasin peak)', 'The Ngorongoro Conservation Area is a protected area and UNESCO World Heritage Site located in the Crater Highlands of northeastern Tanzania. The area is named after Ngorongoro Crater, a large volcanic caldera formed when a giant volcano exploded and collapsed 2-3 million years ago. The crater floor, 600 meters deep and covering 260 square kilometers, is home to approximately 25,000 large animals. The conservation area also includes Olduvai Gorge, one of the most important paleoanthropological sites in the world. Unlike national parks, the Ngorongoro Conservation Area allows human habitation, with Maasai pastoralists living alongside wildlife.', 'Designated as a UNESCO World Heritage Site in 1979 and as an International Biosphere Reserve in 1981. The area was originally part of Serengeti National Park until it was separated in 1959 to create a multiple land use area.', NULL, b'1', -3.2000000, 'Crater Highlands, 180 km west of Arusha City', 35.4500000, 'Ngorongoro Conservation Area', '6:00 AM - 6:00 PM daily', 'CONSERVATION_AREA', NULL, 'Arusha', 'Home to the world\'s largest intact volcanic caldera and one of Africa\'s most spectacular wildlife viewing areas with the highest density of predators.', '8,292 km²', 'ngorongoro-conservation-area', 'Crater, UNESCO World Heritage, Big Five, Black Rhino, Maasai Culture, Olduvai Gorge, Volcanic Caldera, Wildlife Dense', '2025-12-31 23:59:37.000000', 'Ranges from short grass plains on the crater floor to montane forests on the crater rim. Includes fever tree forests, highland grasslands, and diverse plant communities supporting various ecological niches.', 'The crater hosts approximately 25,000 large mammals including the Big Five. It has the densest known population of lions in the world. The area is one of the few places in Africa where you can see the endangered black rhinoceros. Other species include elephants, buffaloes, hippos, wildebeest, zebras, elands, gazelles, and over 500 bird species including flamingos on Lake Magadi.'),
(3, 'Accessible by road from Arusha (2 hours). Main entrance at the northern gate. Good tarmac road to the park entrance.', 'June to October (dry season - best for wildlife concentration)', '2025-12-31 23:59:37.000000', 'Babati', 'Acacia woodlands, riverine forests, seasonal swamps, open grasslands, and ancient baobab-studded landscapes. The Tarangire River and Silale Swamp are key ecosystem features.', '900-1,250 meters', 'Tarangire National Park is Tanzania\'s sixth-largest national park, covering 2,850 square kilometers. Named after the Tarangire River that flows through the park, it serves as a vital water source during the dry season, attracting massive concentrations of wildlife. The park is renowned for having one of the highest elephant populations in Tanzania, with herds of up to 300 elephants common during the dry season. Ancient baobab trees dot the landscape, some over 1,000 years old. During the dry season (June-October), Tarangire has wildlife densities second only to Ngorongoro Crater.', 'Established as a national park in 1970. The area has been important to wildlife migration patterns for millennia, particularly for elephants moving between seasonal water sources.', NULL, b'1', -3.8333000, 'Northern Tanzania, 118 km southwest of Arusha', 36.0000000, 'Tarangire National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Manyara', 'Famous for its huge elephant population, iconic baobab trees, and spectacular concentration of wildlife during the dry season.', '2,850 km²', 'tarangire-national-park', 'Elephants, Baobab Trees, Bird Watching, Wildlife, Dry Season Safari, Tarangire River, Migration, Big Cats', '2025-12-31 23:59:37.000000', 'Dominated by ancient baobab trees, umbrella acacias, and sausage trees. Swamp areas feature dense vegetation including palms and tall grasses. Open plains with scattered acacias.', 'Home to large elephant herds (up to 3,000 individuals), lions, leopards, cheetahs, and over 550 bird species making it a paradise for bird watchers. Other mammals include buffaloes, giraffes, wildebeest, zebras, impalas, elands, fringe-eared oryx, and pythons in the swamps.'),
(4, 'Accessible by road from Arusha (2 hours). Located on the main route to Serengeti and Ngorongoro. Good tarmac road to park entrance.', 'Year-round destination; July to October and January to February best for wildlife', '2025-12-31 23:59:37.000000', 'Monduli', 'Diverse ecosystems including groundwater forest, acacia woodland, open grassland, swamps, and the alkaline lake. The Great Rift Valley escarpment forms a dramatic backdrop.', '960-1,828 meters', 'Lake Manyara National Park is a compact gem located between Lake Manyara and the Great Rift Valley escarpment. Despite its small size, it hosts remarkable biodiversity. The park is famous for its unusual tree-climbing lions, which lounge in acacia branches during the heat of the day. The alkaline lake attracts thousands of flamingos, creating spectacular pink shores during certain seasons. The groundwater forest at the park entrance is one of the few in East Africa.', 'Established as a national park in 1960. The area was previously a hunting ground and gained protection due to its unique wildlife and ecological importance.', NULL, b'1', -3.5333000, 'Northern Tanzania, 126 km west of Arusha, near Great Rift Valley escarpment', 35.8333000, 'Lake Manyara National Park', '6:30 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Manyara', 'Famous for its tree-climbing lions, large flocks of flamingos, and stunning location at the base of the Great Rift Valley escarpment.', '330 km² (including 230 km² of lake surface)', 'lake-manyara-national-park', 'Tree-climbing Lions, Flamingos, Great Rift Valley, Bird Watching, Groundwater Forest, Elephants, Diverse Ecosystems', '2025-12-31 23:59:37.000000', 'Groundwater forest with mahogany and wild mango trees at the park entrance. Acacia woodlands dominate the drier areas. Lush vegetation supported by underground water sources from the escarpment.', 'Tree-climbing lions are the park\'s most famous residents. Large elephant herds, buffaloes, giraffes, zebras, wildebeest, hippos, and a remarkable variety of primates including baboons and blue monkeys. Over 400 bird species recorded.'),
(5, 'Accessible by road from Arusha (45 minutes). Multiple entry gates including Momella Gate and Ngongongare Gate.', 'Year-round; June to February best for Mount Meru trekking', '2025-12-31 23:59:37.000000', 'Arusha', 'Diverse habitats including montane forest, highland moorland, alpine desert, crater floor, alkaline lakes, and open grassland.', '1,500-4,566 meters (Mount Meru summit)', 'Arusha National Park, though small at 137 square kilometers, offers incredible diversity within close proximity to Arusha city. The park is dominated by Mount Meru, an active volcano and Tanzania\'s second-highest mountain at 4,566 meters. The park features three distinct areas: Ngurdoto Crater, the Momella Lakes, and Mount Meru. It is one of the few parks in Tanzania where walking safaris are permitted.', 'Established as a national park in 1960, initially as Ngurdoto Crater National Park. Expanded in 1967 to include Mount Meru and renamed Arusha National Park.', NULL, b'1', -3.2500000, 'Northern Tanzania, 32 km northeast of Arusha City', 36.8333000, 'Arusha National Park', '6:30 AM - 6:30 PM daily', 'NATIONAL_PARK', NULL, 'Arusha', 'Home to Mount Meru (4,566m), Tanzania\'s second-highest peak, featuring stunning landscapes, diverse wildlife, and unique walking safari opportunities.', '137 km²', 'arusha-national-park', 'Mount Meru, Trekking, Colobus Monkeys, Walking Safari, Ngurdoto Crater, Momella Lakes, Bird Watching, Alpine', '2025-12-31 23:59:37.000000', 'Montane forest with tall trees on Mount Meru slopes. Highland moorland and alpine vegetation at higher elevations. Grasslands and swamps around Momella Lakes.', 'Black and white colobus monkeys, blue monkeys, elephants, buffaloes, giraffes, leopards, spotted hyenas, and the rare red duiker. Over 400 bird species.'),
(6, 'Main gate at Marangu. Other gates: Machame, Londorossi, Lemosho, Rongai, Umbwe. Accessible from Moshi (1 hour).', 'January to March and June to October (dry seasons for climbing)', '2025-12-31 23:59:37.000000', 'Moshi Rural', 'Five distinct vegetation zones creating unique habitats from lowland to montane zones.', '1,800-5,895 meters (Uhuru Peak)', 'Kilimanjaro National Park was established to protect Mount Kilimanjaro, Africa\'s highest peak at 5,895 meters and the world\'s tallest free-standing mountain. The mountain features five distinct climatic zones from cultivated farmland through rainforest, heath and moorland, alpine desert, to the arctic summit zone with glaciers. Over 35,000 people attempt to reach Uhuru Peak annually. UNESCO World Heritage Site.', 'Established as a national park in 1973 and designated a UNESCO World Heritage Site in 1987. First summited by Hans Meyer and Ludwig Purtscheller in 1889.', NULL, b'1', -3.0674000, 'Northern Tanzania, near Kenyan border, 128 km from Arusha', 37.3556000, 'Kilimanjaro National Park', '24 hours (climbers register during day)', 'NATIONAL_PARK', NULL, 'Kilimanjaro', 'Home to Mount Kilimanjaro, Africa\'s highest mountain at 5,895 meters, and the world\'s tallest free-standing mountain.', '1,668 km²', 'kilimanjaro-national-park', 'Mount Kilimanjaro, Uhuru Peak, Trekking, UNESCO World Heritage, Africa Highest Mountain, Glaciers, Alpine, Seven Summits', '2025-12-31 23:59:37.000000', 'Montane forest, heath zone with giant heathers, moorland with tussock grasses, alpine zone with giant groundsels and lobelias, glaciers at summit.', 'Elephants, buffaloes, leopards, bushbucks, red duikers, and various primates in lower forests. Over 140 bird species.'),
(7, 'Accessible by air to Mtemere, Kiba, or Siwandu airstrips. Road from Dar es Salaam (5-6 hours).', 'June to October (dry season)', '2025-12-31 23:59:37.000000', 'Liwale', 'Miombo woodland, riverine forests, open grasslands, seasonal swamps, and the Rufiji River system.', '100-1,300 meters', 'Nyerere National Park, created in 2019 from the northern portion of the Selous Game Reserve, is Tanzania\'s largest national park at 30,893 square kilometers. The Rufiji River flows through creating a network of channels, lakes, and swamps. UNESCO World Heritage Site with relatively few tourists.', 'Originally established as a game reserve in 1905. Designated UNESCO World Heritage Site in 1982. Northern sector declared Nyerere National Park in 2019.', NULL, b'1', -7.6667000, 'Southern Tanzania, 219 km from Dar es Salaam', 37.6167000, 'Nyerere National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Morogoro, Ruvuma, and Lindi', 'Africa\'s largest game reserve and UNESCO World Heritage Site, renamed in 2019 to honor President Julius Nyerere.', '30,893 km²', 'nyerere-national-park', 'UNESCO World Heritage, Rufiji River, Wild Dogs, Wilderness, Boat Safari, Elephants, Remote, Nyerere', '2025-12-31 23:59:37.000000', 'Miombo woodland, borassus palms along rivers, grasslands, and riverine forests with mahogany and ebony trees.', 'Over 15,000 elephants, lions, leopards, wild dogs, buffaloes, hippos, crocodiles. Tanzania\'s largest population of endangered African wild dogs. Over 440 bird species.'),
(8, 'Accessible by air to Msembe airstrip. Road from Iringa (4-5 hours on rough roads).', 'June to October (dry season)', '2025-12-31 23:59:37.000000', 'Iringa', 'Miombo woodland, acacia savanna, riverine forests, baobab-studded plains, and the Great Ruaha River valley.', '750-1,868 meters', 'Ruaha National Park is Tanzania\'s largest national park at 20,226 square kilometers. The park is famous for its large elephant population (over 12,000) and has one of the highest concentrations of elephants in East Africa. Renowned for predators, particularly lions. Remote and uncrowded.', 'Originally part of Rungwa Game Reserve in 1910. Upgraded to national park in 1964. Expanded in 2008.', NULL, b'1', -7.9000000, 'Central-southern Tanzania, 130 km from Iringa', 34.8333000, 'Ruaha National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Iringa and Dodoma', 'Tanzania\'s largest national park, featuring the Great Ruaha River and one of Africa\'s largest elephant populations.', '20,226 km²', 'ruaha-national-park', 'Elephants, Lions, Great Ruaha River, Remote, Wild Dogs, Baobabs, Predators, Wilderness', '2025-12-31 23:59:37.000000', 'Miombo woodland, ancient baobabs, acacia species, riverine forests, and Commiphora-Combretum woodlands.', 'Over 12,000 elephants, 30,000+ buffaloes, 10% of Africa\'s lions, leopards, cheetahs, wild dogs. Over 571 bird species.'),
(9, 'Main gate from Dar es Salaam (4-5 hours) via Morogoro. Park bisected by Dar-Iringa highway.', 'Year-round; June to October best for wildlife', '2025-12-31 23:59:37.000000', 'Kilosa', 'Open grassland plains, miombo woodland, acacia savanna, and riverine forests.', '550-1,250 meters', 'Mikumi National Park covers 3,230 square kilometers. Most accessible southern park, 4-5 hours from Dar es Salaam. The Mkata River floodplain is compared to the Serengeti. Excellent year-round wildlife viewing.', 'Established as a national park in 1964. Originally part of the Selous ecosystem.', NULL, b'1', -7.3833000, 'Southern-central Tanzania, 283 km west of Dar es Salaam', 36.9000000, 'Mikumi National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Morogoro', 'The fourth-largest national park, known for reliable wildlife viewing along the main Dar es Salaam-Iringa highway.', '3,230 km²', 'mikumi-national-park', 'Accessible, Mkata Floodplain, Elephants, Lions, Bird Watching, Uluguru Mountains', '2025-12-31 23:59:37.000000', 'Mkata floodplain grasslands, miombo woodland, acacia trees, borassus palms, and riverine forests.', 'Elephants, buffaloes, giraffes, zebras, wildebeest, lions, leopards, wild dogs. Over 400 bird species.'),
(10, 'Main entrance at Mang\'ula village, 65 km from Mikumi or 350 km from Dar es Salaam.', 'Year-round; June to October for hiking', '2025-12-31 23:59:37.000000', 'Kilolo', 'Tropical rainforest, montane forest, miombo woodland, grassland plateaus, streams, and waterfalls.', '250-2,576 meters (Luhombero Peak)', 'Udzungwa Mountains National Park protects 1,990 square kilometers of Eastern Arc Mountains. Unique as it has no roads - explored only on foot. Endemic species including Iringa red colobus and Sanje mangabey. Sanje Waterfall plunges 170 meters.', 'Gazetted as national park in 1992. Previously a forest reserve.', NULL, b'1', -7.7500000, 'Southern-central Tanzania, 350 km southwest of Dar es Salaam', 36.5000000, 'Udzungwa Mountains National Park', '7:00 AM - 5:00 PM daily', 'NATIONAL_PARK', NULL, 'Morogoro', 'A biodiversity hotspot featuring pristine rainforest, endemic primates, spectacular waterfalls, and excellent hiking.', '1,990 km²', 'udzungwa-mountains-national-park', 'Hiking, Waterfalls, Endemic Species, Primates, Rainforest, Biodiversity Hotspot, Eastern Arc', '2025-12-31 23:59:37.000000', 'Pristine tropical rainforest, montane forest, highland grasslands, rich understory vegetation.', 'Six primate species including endemic Iringa red colobus and Sanje mangabey. Forest elephants, buffaloes. Over 400 bird species.'),
(11, 'Accessible by air to Ikuu airstrip. Road access difficult, 40 km from Mpanda.', 'June to October (dry season)', '2025-12-31 23:59:37.000000', 'Mpanda', 'Katuma River floodplains, seasonal lakes, miombo woodland, riverine forests, open grasslands.', '900-1,200 meters', 'Katavi National Park is Tanzania\'s third-largest park and one of its most remote. Famous for highest concentrations of hippos and crocodiles in Africa. Buffalo herds can number in the thousands. Remote with more lions than tourists.', 'Established as national park in 1974. Named after spirit Katabi believed to have lived in tamarind tree near Lake Katavi.', NULL, b'1', -6.9167000, 'Western Tanzania, 40 km south of Mpanda', 31.2000000, 'Katavi National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Katavi', 'One of Tanzania\'s most remote wilderness areas, famous for huge buffalo herds and hippo concentrations.', '4,471 km²', 'katavi-national-park', 'Remote, Wilderness, Buffalo Herds, Hippos, Crocodiles, Western Circuit, Unspoiled', '2025-12-31 23:59:37.000000', 'Miombo woodland, floodplain grasslands, palm-fringed pools, riverine forests.', 'Huge buffalo herds (1,000+), densest hippo/crocodile concentrations, elephants, lions, leopards, giraffes. Over 400 bird species.'),
(12, 'Accessible only by boat or flight. 2-3 hour boat from Kigoma. No roads.', 'May to October (dry season)', '2025-12-31 23:59:37.000000', 'Kigoma Rural', 'Montane forest, lowland rainforest, miombo woodland, grassland, bamboo forests, Lake Tanganyika shoreline.', '772-2,462 meters (Mount Nkungwe)', 'Mahale Mountains National Park protects 1,613 square kilometers on Lake Tanganyika shores. Home to approximately 1,000 wild chimpanzees with one habituated group. Completely remote with no roads - access only by boat. Crystal-clear waters offer excellent snorkeling.', 'Established as national park in 1985. Japanese primatologist Dr. Toshisada Nishida began chimpanzee research in 1960s.', NULL, b'1', -6.2500000, 'Western Tanzania, Lake Tanganyika shore, 120 km south of Kigoma', 29.9167000, 'Mahale Mountains National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Kigoma', 'A remote paradise on Lake Tanganyika, home to wild chimpanzees, accessible only by boat.', '1,613 km²', 'mahale-mountains-national-park', 'Chimpanzees, Lake Tanganyika, Remote, Primate Trekking, Snorkeling, Mountains, Western Circuit', '2025-12-31 23:59:37.000000', 'Montane evergreen forest, lowland rainforest, miombo woodland, bamboo at higher elevations.', '1,000 wild chimpanzees, eight other primate species, leopards, bushbucks. Over 355 bird species. Lake has 250+ endemic fish species.'),
(13, 'Accessible only by boat from Kigoma (30 minutes to 1 hour). No road access.', 'Year-round; June to October best for chimpanzees', '2025-12-31 23:59:37.000000', 'Kigoma Rural', 'Lowland evergreen forest in valleys, miombo woodland on ridges, grassland plateaus, Lake Tanganyika shoreline.', '772-1,500 meters', 'Gombe Stream is Tanzania\'s smallest park at 52 square kilometers but globally renowned as Dr. Jane Goodall\'s chimpanzee research site since 1960 - the world\'s longest-running wildlife research project. About 100 habituated chimpanzees live in Gombe.', 'Established as game reserve in 1943, upgraded to national park in 1968. Jane Goodall arrived in 1960.', NULL, b'1', -4.6667000, 'Western Tanzania, Lake Tanganyika shore, 16 km north of Kigoma', 29.6167000, 'Gombe Stream National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Kigoma', 'Tanzania\'s smallest park, world-famous as Jane Goodall\'s chimpanzee research site since 1960.', '52 km²', 'gombe-stream-national-park', 'Chimpanzees, Jane Goodall, Research, Lake Tanganyika, Primates, Western Circuit, Small Park', '2025-12-31 23:59:37.000000', 'Gallery forest in valleys, miombo woodland on slopes, grasslands on plateaus.', '100 chimpanzees with habituated groups, red-tailed monkeys, red colobus, blue monkeys, olive baboons, bushbucks. Over 200 bird species.'),
(14, 'Accessible by boat from Nkome (3.5 hours) or Muganza (1 hour). Fly to Rubondo airstrip.', 'Year-round; June to October for chimpanzees and fishing', '2025-12-31 23:59:37.000000', 'Biharamulo', 'Closed-canopy tropical forest, papyrus wetlands, savanna, rocky shores, sandy beaches, Lake Victoria waters.', '1,134-1,486 meters', 'Rubondo Island National Park comprises islands in Lake Victoria. 90% covered in dense forest. Unique as successful wildlife introduction site with chimpanzees introduced in 1960s. One of few places to observe wild chimpanzees and spot sitatunga. Over 400 bird species.', 'Declared national park in 1977. Wildlife introduction site starting in 1960s under Frankfurt Zoological Society.', NULL, b'1', -2.3000000, 'Northwestern Tanzania, island in Lake Victoria, west of Mwanza', 31.8333000, 'Rubondo Island National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Geita', 'A pristine island in Lake Victoria, offering unique forest-lake ecosystems with introduced chimps and rare sitatunga.', '457 km²', 'rubondo-island-national-park', 'Island, Lake Victoria, Chimpanzees, Sitatunga, Bird Watching, Fishing, Remote, Forest', '2025-12-31 23:59:37.000000', 'Dense tropical forest with mahogany and fig trees, papyrus swamps, open grasslands, aquatic vegetation.', 'Introduced chimpanzees, elephants, giraffes, suni, roan antelopes. Indigenous sitatunga, hippos, crocodiles, otters, bushbucks. Over 400 bird species.'),
(15, 'Accessible by road from Dar es Salaam (2.5-3 hours). Also by boat along coast or Wami River.', 'Year-round; June to October for wildlife; November to February for turtles', '2025-12-31 23:59:37.000000', 'Bagamoyo and Pangani', 'Beaches, mangrove forests, salt flats, acacia woodlands, riverine forests, grasslands, Wami River system.', '0-200 meters', 'Saadani National Park is unique as Tanzania\'s only coastal wildlife sanctuary where beach meets bush. Covers 1,062 square kilometers with 30 kilometers of Indian Ocean coastline. Hosts four of the Big Five. Beaches are important green turtle nesting sites. Historic Saadani village was once a 19th-century trading port.', 'Gazetted as national park in 2005, combining Saadani Game Reserve, Mkwaja Ranch, Wami River, and Zaraninge Forest.', NULL, b'1', -6.0000000, 'Coastal Tanzania, 45 km north of Bagamoyo, 100 km north of Dar es Salaam', 38.7667000, 'Saadani National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Pwani', 'Tanzania\'s only wildlife sanctuary bordering the Indian Ocean, combining beach and bush safari.', '1,062 km²', 'saadani-national-park', 'Beach, Coastal, Ocean, Unique, Wami River, Turtles, Boat Safari, Historic, Beach Safari', '2025-12-31 23:59:37.000000', 'Coastal mangrove forests, acacia woodlands, palm trees, riverine vegetation, coastal dune vegetation.', 'Four of Big Five: elephants, lions, leopards, buffaloes. Giraffes, wildebeest, hippos, crocodiles, green turtles. Over 300 bird species.'),
(16, 'Accessible by air (30-minute flight from Dar) or boat. Main settlements: Kilindoni, Utende, Chole Island.', 'Year-round; October to March for whale sharks', '2025-12-31 23:59:37.000000', 'Mafia', 'Coral reefs, seagrass beds, mangrove forests, tidal channels, sandy beaches, open ocean.', '0-50 meters', 'Mafia Island Marine Park, established in 1995 as Tanzania\'s first marine park, protects 822 square kilometers. Globally renowned for whale shark encounters (October to March). Coral reefs support over 400 fish species. Five sea turtle species nest on beaches. UNESCO World Heritage Site.', 'Gazetted in 1995 as Tanzania\'s first marine park. Historical significance with 13th-century ruins.', NULL, b'1', -7.9167000, 'Indian Ocean, 120 km southeast of Dar es Salaam', 39.7500000, 'Mafia Island Marine Park', 'Accessible 24/7', 'MARINE_PARK', NULL, 'Pwani', 'Tanzania\'s first marine protected area, renowned for pristine coral reefs, whale sharks, and world-class diving.', '822 km²', 'mafia-island-marine-park', 'Marine Park, Diving, Snorkeling, Whale Sharks, Coral Reefs, Sea Turtles, Island, Indian Ocean', '2025-12-31 23:59:37.000000', 'Extensive seagrass beds, eight mangrove species, diverse hard and soft coral species.', 'Over 400 fish species, whale sharks (seasonal), manta rays, five sea turtle species, dolphins, dugongs (rare), humpback whales (seasonal).'),
(17, 'Accessible from Mtwara town (20 km). Fly to Mtwara from Dar or drive (10-12 hours).', 'Year-round; June to October for diving; November to February for turtles', '2025-12-31 23:59:37.000000', 'Mtwara Rural', 'Coral reefs, extensive mangrove forests, seagrass meadows, sandy beaches, rocky shores, Ruvuma River estuary.', '0-100 meters', 'Mnazi Bay-Ruvuma Estuary Marine Park protects 650 square kilometers at Tanzania\'s southern border extending to Mozambique. Established in 2000, it\'s one of Tanzania\'s most pristine marine areas. Five sea turtle species nest on beaches. Excellent snorkeling and diving with minimal tourist pressure.', 'Gazetted as marine park in 2000. Minimal development preserves wild character.', NULL, b'1', -10.3833000, 'Far southern Tanzania, 396 km south of Dar es Salaam, near Mozambique border', 40.3500000, 'Mnazi Bay-Ruvuma Estuary Marine Park', 'Accessible 24/7', 'MARINE_PARK', NULL, 'Mtwara', 'A pristine marine park at Tanzania\'s southern border with diverse coral reefs, mangroves, and turtle nesting sites.', '650 km²', 'mnazi-bay-ruvuma-estuary-marine-park', 'Marine Park, Remote, Pristine, Diving, Snorkeling, Sea Turtles, Mangroves, Coral Reefs', '2025-12-31 23:59:37.000000', 'Extensive mangrove forests (nine species), seagrass beds, diverse coral species, coastal vegetation.', 'Over 400 fish species, five sea turtle species, humpback whales (seasonal), dolphins, dugongs (rare), rays.'),
(18, 'Main gate at Zange, 112 km from Moshi. Accessible from Arusha (5-6 hours) or from Dar via Tanga.', 'June to February', '2025-12-31 23:59:37.000000', 'Same', 'Acacia-commiphora bushland, open grasslands, rocky hills, seasonal rivers, baobab-studded landscapes.', '230-1,570 meters', 'Mkomazi National Park covers 3,245 square kilometers forming continuous ecosystem with Kenya\'s Tsavo West. Upgraded to national park in 2008. Significant for black rhino sanctuary and African wild dog conservation programs. Spectacular views of Kilimanjaro and Usambara Mountains. Undervisited wilderness.', 'Originally gazetted as game reserve in 1951. Upgraded to national park in 2008. Black rhino sanctuary established 1997.', NULL, b'1', -4.2500000, 'Northern Tanzania, 112 km from Moshi, borders Kenya', 37.9167000, 'Mkomazi National Park', '6:00 AM - 6:00 PM daily', 'NATIONAL_PARK', NULL, 'Kilimanjaro and Tanga', 'A vital sanctuary for endangered black rhinos and African wild dogs with spectacular Kilimanjaro views.', '3,245 km²', 'mkomazi-national-park', 'Black Rhino, Wild Dogs, Conservation, Kilimanjaro Views, Endangered Species, Remote, Northern Circuit', '2025-12-31 23:59:37.000000', 'Acacia and commiphora bushland, ancient baobabs, grasslands with scattered trees, vegetation adapted to semi-arid conditions.', 'Black rhinos (in sanctuary), African wild dogs (breeding program), elephants, giraffes, elands, lesser kudu, gerenuk, fringe-eared oryx, lions, leopards. Over 450 bird species.');

-- --------------------------------------------------------

--
-- Table structure for table `parks_activities`
--

CREATE TABLE `parks_activities` (
  `created_at` datetime(6) NOT NULL,
  `notes` text DEFAULT NULL,
  `activity_id` bigint(20) NOT NULL,
  `park_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `activities`
--
ALTER TABLE `activities`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UK5wuw0l1c8guktttfs0ta0g76n` (`name`),
  ADD UNIQUE KEY `UKju6qornwtyfq2iosjfjuvyhuc` (`slug`),
  ADD KEY `idx_name` (`name`),
  ADD KEY `idx_web_active` (`is_web_active`),
  ADD KEY `idx_has_tariff` (`has_tariff`),
  ADD KEY `idx_slug` (`slug`);

--
-- Indexes for table `parks`
--
ALTER TABLE `parks`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `UKowqaoi8fldr8cw7eifnejvie9` (`name`),
  ADD UNIQUE KEY `UKj8i6xv55xl1x16qqft12q1ki3` (`slug`),
  ADD KEY `idx_park_type` (`park_type`),
  ADD KEY `idx_region` (`region`),
  ADD KEY `idx_is_active` (`is_active`),
  ADD KEY `idx_name` (`name`);

--
-- Indexes for table `parks_activities`
--
ALTER TABLE `parks_activities`
  ADD PRIMARY KEY (`activity_id`,`park_id`),
  ADD KEY `idx_park_id` (`park_id`),
  ADD KEY `idx_activity_id` (`activity_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `activities`
--
ALTER TABLE `activities`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT for table `parks`
--
ALTER TABLE `parks`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `parks_activities`
--
ALTER TABLE `parks_activities`
  ADD CONSTRAINT `FK7w34ypkvov4g7tn7ncqmiqe40` FOREIGN KEY (`park_id`) REFERENCES `parks` (`id`),
  ADD CONSTRAINT `FKdfq5aspddocmeytjmekhtaveb` FOREIGN KEY (`activity_id`) REFERENCES `activities` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
