package com.itineraryledger.kabengosafaris.Expense.Controller;

import com.itineraryledger.kabengosafaris.Expense.DTOs.ExpenseDocumentDTOs.UpdateExpenseDocumentDTO;
import com.itineraryledger.kabengosafaris.Expense.DTOs.ExpenseDocumentDTOs.UploadExpenseDocumentDTO;
import com.itineraryledger.kabengosafaris.Expense.Services.ExpenseDocumentServices.*;
import com.itineraryledger.kabengosafaris.Response.ApiResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Expense documents — proof-of-payment files attached to an Expense (or to a
 * specific ExpensePayment within it).
 *
 * Two routes:
 *   /api/expenses/{expenseId}/documents          — list + upload
 *   /api/expense-documents/{id}                  — single doc get / file / update / delete
 *
 * Mirrors the InvoiceDocumentController split.
 */
@RestController
@Slf4j
@RequiredArgsConstructor
public class ExpenseDocumentController {

    private final ExpenseDocumentGetService getService;
    private final ExpenseDocumentUploadService uploadService;
    private final ExpenseDocumentUpdateService updateService;
    private final ExpenseDocumentDeleteService deleteService;

    // ---------------------------------------------------------------------
    // Per-expense scope
    // ---------------------------------------------------------------------

    @GetMapping("/api/expenses/{expenseId}/documents")
    @PreAuthorize("hasAuthority('PERM_READ_EXPENSE_DOCUMENT') or hasAuthority('PERM_READ_EXPENSE')")
    public ResponseEntity<ApiResponse<?>> listForExpense(@PathVariable String expenseId) {
        return getService.listForExpense(expenseId);
    }

    @PostMapping(value = "/api/expenses/{expenseId}/documents",
            consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasAuthority('PERM_CREATE_EXPENSE_DOCUMENT')")
    public ResponseEntity<ApiResponse<?>> uploadDocument(
            @PathVariable String expenseId,
            @ModelAttribute UploadExpenseDocumentDTO dto) {
        log.info("POST /api/expenses/{}/documents — uploading expense document", expenseId);
        return uploadService.uploadDocument(expenseId, dto);
    }

    // ---------------------------------------------------------------------
    // Single-doc operations (independent of expense path so the file URL
    // generated by the upload service is stable regardless of where the
    // browser ended up navigating).
    // ---------------------------------------------------------------------

    @GetMapping("/api/expense-documents/{id}")
    @PreAuthorize("hasAuthority('PERM_READ_EXPENSE_DOCUMENT') or hasAuthority('PERM_READ_EXPENSE')")
    public ResponseEntity<ApiResponse<?>> getDocument(@PathVariable String id) {
        return getService.getById(id);
    }

    @GetMapping("/api/expense-documents/{id}/file")
    @PreAuthorize("hasAuthority('PERM_READ_EXPENSE_DOCUMENT') or hasAuthority('PERM_READ_EXPENSE')")
    public ResponseEntity<?> downloadFile(@PathVariable String id) {
        return getService.downloadFile(id);
    }

    @PutMapping("/api/expense-documents/{id}")
    @PreAuthorize("hasAuthority('PERM_UPDATE_EXPENSE_DOCUMENT')")
    public ResponseEntity<ApiResponse<?>> updateDocument(
            @PathVariable String id,
            @RequestBody UpdateExpenseDocumentDTO dto) {
        return updateService.updateDocument(id, dto);
    }

    @DeleteMapping("/api/expense-documents")
    @PreAuthorize("hasAuthority('PERM_DELETE_EXPENSE_DOCUMENT')")
    public ResponseEntity<ApiResponse<?>> deleteDocuments(@RequestParam("ids") List<String> ids) {
        return deleteService.deleteDocuments(ids);
    }
}
