-- ON_HOLD has to exist in the column, not just in Java (2026-10-09).
--
-- V23 added the two hold columns and the application deployed clean, so the workflow looked shipped.
-- The first hold came back "Database operation failed": invoices.status is a native MySQL enum,
-- generated by ddl-auto when the baseline was taken, and it lists the six states that existed then.
-- Writing a seventh is a data truncation error, raised at commit rather than in the service, which
-- is why it surfaced as a bare DataAccessException with nothing pointing at the cause.
--
-- ddl-auto=update does not widen an existing enum. It adds tables and columns and leaves types
-- alone, so nothing was ever going to fix this at boot.
--
-- Every @Enumerated(STRING) column in this schema is an enum of the values that existed when the
-- baseline was taken. Adding a constant to any of those Java enums needs a migration like this one,
-- and AnEnumValueExistsInTheColumnTest now fails the build when one is missing.
--
alter table invoices
    modify column status enum (
        'CANCELLED','DRAFT','ON_HOLD','OVERDUE','PAID','PARTIALLY_PAID','SENT'
    ) not null;
